# main.py
W_WIDTH = 300
W_HEIGHT = 300
W_HALF_WIDTH = W_WIDTH / 2
W_HALF_HEIGHT = W_HEIGHT / 2
SCALE = 3
TILE_SIZE = 8

# camera.py
FOV = 70
ASPECT = W_WIDTH / W_HEIGHT
NEAR = 0.1
FAR = 50
SENSITIVITY = 0.1